# Makefile variable
GCC_PREFIX=arm-linux-gnueabihf-
JOBS=4

# path to needed directories
LINUX_DIR=linux-sunxi
UBOOT_DIR=u-boot-sunxi
CHROOT_DIR=chroot-armhf

# user defined variable for the target system
HOSTNAME=A10
PACKAGES="ntp sudo"

# target device on which to write the prepared system
SDCARD_DEVICE=/dev/sdc
